### ISSUE TITLE
Mapping boolean property fails

### ISSUE THREAD

**Issue by dstollie** [CupCoffee/Reify#5]
In #4  ive sumbitted some basic tests. While running the tests, one test case fails because it did not map a property correctly to a boolean.

Whenever you try to map a "1" to a boolean, you would expect it to be true, this is not the case. I think this should be fixed

**Comment by CupCoffee** [comment]
I created a pull request #9  implementing the casting of values to their respective type

**Comment by CupCoffee** [comment]
I've added primitive casting for a known types in PHP. This issue will be closed.
