### ISSUE TITLE
Mapping collection or normall class

### ISSUE THREAD

**Issue by dstollie** [CupCoffee/Reify#7]
To me its unclear how reify should map an empty array. ie

```php
return (new Mapper())->map(new ArrayMapper(), [])->to(Person::class);
```

Should it now map to a empty array with no person objects or should it map to a empty person object? 

An other possibility could be to seperate the mapping from concrete class and of a an array and let the developer itself decided how he wants to map.

Here is a branch with that added:

https://github.com/dstollie/Mapper/tree/map_collection

**Comment by CupCoffee** [comment]
At the moment the decision wether the data should be mapped to a single object or array is based on the data given being an associative array in other words, *not* having numeric keys.

This makes sense until the data passed to the mapper is empty. Then, there is no logical way to decide how to map the data.

One proposition i have is changing the to() method. If you want the data to be mapped to an array, the following syntax could be used:

`(new Mapper())->map(new ArrayMapper(), [])->to([Person::class]);`
The array supplied would support only 1 element.

If you want the data to be mapped to a single instance:

`(new Mapper())->map(new ArrayMapper(), [])->to(Person::class);`

**Comment by dstollie** [comment]
After a personal discussion with you, I think the best solution would be to separate the mapping of a concrete class and the mapping of an array. For example

```php
(new Mapper())->mapArray(new ArrayMapper(), [])->to(Person::class);
(new Mapper())->map(new ArrayMapper(), [])->to(Person::class);
```

**Comment by CupCoffee** [comment]
I created a pull request with the discussed feature

https://github.com/CupCoffee/Reify/pull/10

**Comment by CupCoffee** [comment]
Feature has been tested and merged
